apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort # Default if not defined
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000